### ISSUE TITLE
The type * exists in both 'RosBridgeClient' and 'RosBridgeClientUWP,

### ISSUE THREAD

**Issue by araster1010** [EricVoll/ros-sharp#1]
Hello.
Thank you for your active contributions to the ROS# for UWP.

I cloned your project, I got 77 errors.
They are all similar to the errors shown below.

`Assets\RosSharp\Scripts\RosBridgeClient\MessageHandling\LaserScanWriter.cs(40,43): error CS0433: The type 'LaserScan' exists in both 'RosBridgeClient, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'RosBridgeClientUWP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
`

I would appreciate any advice you can give me.

* My OS is: Windows 10 Pro, ver.1909, Build 18363.1016
* My Unity Version is: 2019.4.8f1
* My Build Target Platform is: UWP

Thanks.

**Comment by EricVoll** [comment]
Hi @araster1010 
Thank you for the issue creation.

Could you quickly explain how you fixed your error for future reference for other users?

I suspect, that the configuration of the Dll's in Unity was wrong (set to the wrong build targets) could that be the case?

Best,
Eric

**Comment by araster1010** [comment]
Thank you for your quick reply.
That's right. I updated the dll files setting.

In `Assets/Rosharp/Plugins/RosBridgeClient`, I changed `WSAPlayer` to **disabled**. (Just Editor and Standalone)

In `Assets/Rosharp/Plugins/RosBridgeClientUWP`,  I changed `Editor and Standalone `to **disabled**. (Just WSA Player)
