### ISSUE TITLE
Errors while following "get started" steps

### ISSUE THREAD

**Issue by Rive4** [EricVoll/ros-sharp#10]
Hello,

I'm working with an older ros-sharp branch for Hololens and I saw that you made a newer adaptation of ros-sharp for Hololens.
I was following the steps from the readme and when I imported the RosSharp folder, some errors appeared in Unity console.
![image](https://user-images.githubusercontent.com/25901929/100106469-ddf17f00-2e68-11eb-8aa2-b9eadc02a8bd.png)

I made a script of a simple publisher and compiled the solution. When I tested, the comunication did not work.

I also compiled and deployed the example without success.
Any idea of why I can't comunicate?
Im using Hololens 1, Unity 2019.4.2f1 and ROS Melodic.

Thank you,

**Comment by EricVoll** [comment]
Hi @Rive4 
I am very sorry that I did not respond until now. GitHub didn't send me notifications...

I might have a few ideas why this could happen:
1. Did you also import the Newtonsoft folder, with the AOT compilable versions of Newtonsoft? (The demo project includes that already, so that should actually not be an issue)
2. Are you maybe working with asmdef files, which have missing references to the other namespaces?

sry again - I hope its not too late to solve your issue.

**Comment by Rive4** [comment]
Hi @EricVoll 

Thank you for your answer. I am currently testing with the demo instead of importing the required files from an empty project.
Seem to work the connection (so I could start from this point my projects) but now rosbridge is reporting the following error as output:
`2020-12-21 16:52:29+0100 [-] [ERROR] [1608565949.890468]: [Client 0] Received a message without an op.  All messages require 'op' field with value one of: ['service_response', 'unadvertise_service', 'call_service', 'publish', 'fragment', 'subscribe', 'advertise_service', 'unsubscribe', 'unadvertise', 'advertise'].  Original message was: {}
`
Do you know why this happens? I supose that this could be from publish side in RosSharp where the message is created. Isn't it?

This time I am using the assets from 'ProjectSetup' folder.

Thank you,

**Comment by Rive4** [comment]
Well..., I just saw that I was commiting when I was copying the files. I realized when I randomly found this video a video on YouTube using your repository (https://www.youtube.com/watch?v=mnMYT521uXY&t=1124s).

Thank you for your help.
