### ISSUE TITLE
RosBridgeClient.dll will not be loaded due to errors

### ISSUE THREAD

**Issue by jstiefel** [EricVoll/ros-sharp#13]
Hi @EricVoll 

I'm having the same issue as described here https://github.com/EricVoll/ros-sharp/issues/10 when trying to add ros-sharp to an existing Unity project. I followed the instructions in your repo and the youtube tutorial and already added the Plugins folder with `Newtonsoft.Json AOT`. As a result, I'm also not getting the ROSBridgeClient tab.

![grafik](https://user-images.githubusercontent.com/44534970/121378178-40acf280-c943-11eb-8fb6-fc11753846be.png)

Can this be related to versions? I'm on Unity 2019.4.26 with MRTK 2.6.0.

I also tried the sample project, but got similar errors:

![grafik](https://user-images.githubusercontent.com/44534970/121379832-b2397080-c944-11eb-83aa-e726f0b393f1.png)

**Comment by EricVoll** [comment]
Hi @jstiefel 
I'll have a look. Should be a quick fix.

**Comment by EricVoll** [comment]
Merging the PR closed the issue. If the problem still comes up, let me know. Thanks for creating this issue.
